# .travis.yml
language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v
